### ISSUE TITLE
Auto play

### ISSUE THREAD

**Issue by eddebc** [browser-automation/cba#155]
Is there an option to auto play for a URL/domain?

**Comment by Manvel** [comment]
Hi @eddebc 👋 

No, at this moment there is no way to assign automation to a Domain or Page, Currently execution supports single thread, meaning you can't have multiple automations, but what you can do is to check for the URL in the inject script and based on URL act accordingly, while running automation on a high number repeat, but not sure if this is what you meant, guess you are looking for something more straightforward to use. If you can tell more about your use-case would be great.

**Comment by eddebc** [comment]
@Manvel The usecase is to auto close a site's prompt that comes up every ~10 min on a load event.   
In other words, if ~10 minutes have passed and there is a new page load event, said prompt will pop up.   
  
Your suggestion worked. Thanks!
